### ISSUE TITLE
test_BFAST.r: error in run_udf while creating process graph

### ISSUE THREAD

**Issue by przell** [Open-EO/openeo-usecases#1]
Hi Milutin, 

in the script "test_BFAST.r" do you get this part to run when connected to your backend?
`p$run_udf(data = s2, udf = udfCode, runtime = "R")`
I receive an error directly when this part of the process graph is created (i don't reach the point to send the process graph to our backend): 
```
p$run_udf(data = s2, udf = udfCode, runtime = "R")
 Error in param$setValue(value) : attempt to apply non-function 
```
Also when I replace the udfCode by the following (which works when testing the udf-server outside of openEO):
```
udfCode = quote({
  data2 = data*(2); data2
})
```
Not sure if this is related to our backend or how the r-client calls the process?
@flahn Have you experienced this behaviour?
Best, 
Peter

**Comment by flahn** [comment]
I haven't tested it yet. From the error itself, it seems that setting the value of one of the arguments might be the problem. It might be, that handling the qoute object causes problems or the parameter `udf` in `run_udf` could not be interpreted. For the latter please check the parameter description of `udf` in the process `run_udf`.

Apart from that, which openEO API version is used and which back-end?

**Comment by przell** [comment]
> I haven't tested it yet.

The script "test_BFAST.r" can be used for testing.

> It might be, that handling the qoute object causes problems

I have tried with passing the script "BFAST_udf.R" (from this repo) to `run_udf` and tried with this 
```
udfCode = quote({
  data2 = data*(2); data2
})
```
I will try to play around some more.

>  For the latter please check the parameter description of udf in the process run_udf

The parameter description of run_udf in the Eurac backend is as follows:

```
conn %>% describe_process("run_udf")
Process:	run_udf
Summary:	Run an UDF
Description:	Runs an UDF in one of the supported runtime environments.

The process can either:

1. load and run a locally stored UDF from a file in the workspace of the authenticated user. The path to the UDF file must be relative to the root directory of the user's workspace.
2. fetch and run a remotely stored and published UDF by absolute URI, for example from [openEO Hub](https://hub.openeo.org)).
3. run the source code specified inline as string.

The loaded UDF can be executed in several processes such as ``aggregate_temporal()``, ``apply()``, ``apply_dimension()``, ``filter()`` and ``reduce()``. In this case an array is passed instead of a raster data cube. The user must ensure that the data is properly passed as an array so that the UDF can make sense of it.
Returns:	The data processed by the UDF. Returns a raster data cube if a raster data cube was passed for `data`. If an array was passed for `data`, the returned value is defined by the context and is exactly what the UDF returned.

  Parameter                                                                                               Description Required
1      data                                            The data to be passed to the UDF as array or raster data cube.     TRUE
2       udf                                           Either source code, an absolute URL or a path to an UDF script.     TRUE
3   context                           Additional data such as configuration options that should be passed to the UDF.    FALSE
4   runtime                                                      An UDF runtime identifier available at the back-end.     TRUE
5   version An UDF runtime version. If set to `null`, the default runtime version specified for each runtime is used.    FALSE
```
> Apart from that, which openEO API version is used and which back-end?

```
driver_url = "https://openeo.eurac.edu"
api_versions(url=driver_url)
# A tibble: 2 x 3
  api_version production url                                             
  <chr>       <lgl>      <chr>                                           
1 0.4.2       FALSE      https://openeo.eurac.edu/                       
2 0.3.1       FALSE      http://saocompute.eurac.edu/openEO_0_3_0/openeo/
```

We're using Eurac backend api_version 0.4.2

**Comment by flahn** [comment]
I have released a new version 0.6.1 (current version on master and develop branches), which should fix this issue.

**Comment by MilutinMM** [comment]
We used the new version (0.6.1) to test 'openeo-usecases/WUR_BFAST_UseCase/R/test_BFAST.R' , but now faced other two error messages.

.) The first error message was after validating the graph at the back-end:
`> validate_process_graph(graph=graph_test2)
Endpoint for this function is not supported by the current back-end.` 

.) The second error message was after 'compute_result' process:
`> compute_result(graph=as(graph_test2, "Graph"), format="GTiff", output_file = 'results_test2.tiff')
No method asJSON S3 class: {`

@flahn could you please check if it is related to the R client?

**Comment by m-mohr** [comment]
The first error is pretty clear and correct. EURAC doesn't support validation so you can just remove that line...

What is this `as(graph_test2, "Graph")` by the way? Shouldn't it be just `graph_test2`?

**Comment by flahn** [comment]
I will look into it. 

@m-mohr Since the openEO processes return `ProcessNode` objects, we must define it that way. But I have to look if the coercion is really necessary at that point. Usually you should be able to pass on the final node.

**Comment by m-mohr** [comment]
@flahn I think I'd expect that this is handled by the client automatically and was a bit confused it's not used in the validate... call.

**Comment by flahn** [comment]
And as I expected it, you don't need to coerce it manually. The function does this internally, but you can do it manually.

**Comment by flahn** [comment]
However, i ran the following code:

```R
eurac = connect(host = euracHost)

p = processes()

udfName = "BFAST_udf.R"
udfCode = readChar(udfName, file.info(udfName)$size)

s2 = p$load_collection(id = p$data$openEO_S2_32632_10m_L2A, 
                       spatial_extent = list(west = 11.2792, 
                                             south = 46.4643, 
                                             east = 11.4072, 
                                             north = 46.5182), 
                       temporal_extent = c("2018-06-04T00:00:00Z","2018-06-23T00:00:00Z"))

udf = p$run_udf(data = s2, udf = udfCode, runtime = "R")

result = p$save_result(udf, format="GTiff")

debug()
compute_result(graph=result, format="GTiff", output_file = 'results_test2.tiff')
```

And I get the following:
```
*** Response ***
Status: 401
Headers:
                                                                            
date                                           Tue, 31 Mar 2020 16:00:06 GMT
server                                                     Apache-Coyote/1.1
access-control-allow-origin                                   37.201.170.203
access-control-allow-methods          OPTIONS, GET, POST, DELETE, PUT, PATCH
access-control-allow-headers     origin, content-type, accept, authorization
access-control-allow-credentials                                        true
access-control-expose-headers      Location, OpenEO-Identifier, OpenEO-Costs
www-authenticate                       Authorization header must be provided
content-type                                         text/html;charset=utf-8
content-language                                                          en
content-length                                                           975

Body:
[1] "Other formats not yet implemented."
SERVER-ERROR: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Apache Tomcat/7.0.76 - Error report</title>
<style><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}--></style>
</head>
<body>
<h1>HTTP Status 401 - Unauthorized</h1>
<hr size="1" noshade>
<p><b>type</b> Status report</p>
<p><b>message</b> <u>Unauthorized</u></p>
<p><b>description</b> <u>This request requires HTTP authentication.</u></p>
<hr size="1" noshade>
<h3>Apache Tomcat/7.0.76</h3>
</body>
</html>
```

First, the error message is in XML. Usually all server messages should be JSON. This is the responsibility of EURAC. The message says that you need a login for this, however the credentials provided are invalid (the same for as the ones in our internal document). @przell can you help here?

Apart from that your code failed, because I could not handle the `quote` statement. There is no translation from the quote object into JSON (usually list like structures). The `run_udf` parameter **udf** requires a text or an URL.

**Comment by przell** [comment]
Hi Florian, 
thanks for jumping in!

> First, the error message is in XML. Usually all server messages should be JSON. This is the responsibility of EURAC.

We will have a look at this!

> The message says that you need a login for this, however the credentials provided are invalid (the same for as the ones in our internal document).

I have updated the internal document "openEO back-ends". Under EURAC / WCPS API Version 0.4.2 you can find a new user added here who has the rights to exectue UDFs.
 
> Apart from that your code failed, because I could not handle the quote statement. There is no translation from the quote object into JSON (usually list like structures). The run_udf parameter udf requires a text or an URL.

Thanks for the clarification. This was a snippet taken from some old example.

@flahn and @MilutinMM the list_udf_runtime function in the Eurac backend is currently hardcoded (we will adjust this to be dynamic in the future). So currently the bfast package will not show up in the description. I am checking that the package is available now manually.

**Comment by przell** [comment]
I have updated the code from @flahn above to get to run up to the udf. Then it throws an error we can discuss.
Here the code:
```
library(openeo)
library(dplyr)
euracHost = "https://openeo.eurac.edu"
user = "" # in the google docs
password = "" # in the google docs
api_versions(url=euracHost)

eurac = connect(host = euracHost, 
                user = user, 
                password = password, 
                login_type = "basic")

eurac %>% describe_collection("openEO_S2_32632_10m_L2A_D22")

p = processes()

udfName = "BFAST_udf.R"
udfCode = readChar(udfName, file.info(udfName)$size)

s2 = p$load_collection(id = p$data$openEO_S2_32632_10m_L2A_D22, 
                       spatial_extent = list(west = 11.2792, 
                                             south = 46.4643, 
                                             east = 11.4072, 
                                             north = 46.5182), 
                       temporal_extent = c("2018-06-04T00:00:00Z","2018-06-23T00:00:00Z"))

udf = p$run_udf(data = s2, udf = udfCode, runtime = "R") #"r"
eurac %>% describe_process("run_udf")

#result = p$save_result(s2, format="NETCDF")
result = p$save_result(udf, format="NETCDF")

debug()
graph = as(result,"Graph")
done = compute_result(graph=result, format="NETCDF", output_file = 'results_test2.ncdf')
```
The error occurs in the udf block of the process graph if you call `udf` after defining it as above:
```
> udf
Error in value[[3L]](cond) : 
  Error serializing parameter 'runtime' in process node 'run_udf_BCIXF9752E' :cannot open the connection
In addition: Warning messages:
1: In file(con, "rb") : 'raw = FALSE' but 'R' is not a regular file
2: In file(con, "rb") : cannot open file 'R': it is a directory
```
I will investigate more on this tomorrow. If someone knows directly what this could mean, please share your thoughts.

**Comment by flahn** [comment]
Just a guess, but does the file exist in your workspace (`list.files()`). If you can't find the script, then maybe adapt you workspace (`setwd()`).

**Comment by flahn** [comment]
The fix should also fix https://github.com/Open-EO/openeo-r-client/issues/47.

**Comment by GreatEmerald** [comment]
We tested it and it indeed works now with the develop version of the R client and EURAC backend with version 0.4 API. Though the results are not yet returned properly as per https://github.com/Open-EO/openeo-wcps-driver/issues/40
