### ISSUE TITLE
grant access to use case responsibles

### ISSUE THREAD

**Issue by przell** [Open-EO/openeo-usecases#2]
Hi Milutin and Dainius, 
we discussed to use this repo as the common place to store the use cases.
How should we go about access rights to this repo?
I'd find it easier to have direct access rather than going through the fork/pull-request workflow.
Could we open it for everybody who is part of the openEO repo?
Should it be used as the place to actively work or rather as a place to combine only the final process graphs/scripts?
Best, 
Peter

**Comment by m-mohr** [comment]
Yes, we should grant access to people working on use cases and maybe also rename the repo to openeo-usecases.

**Comment by GreatEmerald** [comment]
Yes, indeed, that should be the case. I can rename it, but I don't see a way to grant access? I think that's an organisation setting or so. I can invite teams, but I don't see a "team" that would include everyone in the organisation...

**Comment by m-mohr** [comment]
Yes, we need to invite on a case by case basis. I just invited przell and claxn and renamed the repo for you. I think several other people have admin permissions on the orga so I guess we just wait for people to ask for access or make PRs.

**Comment by GreatEmerald** [comment]
OK, that's fine for me as well!
