### ISSUE TITLE
Processes in JSON

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-usecases#7]
@MilutinMM @jdries Can you provide the JSON processes / graphs for your use cases? It would help us to do cross back-end tests for D35.

**Comment by jdries** [comment]
@tbanyai  see above, can you provide a json printout of the graph generated by the python code?

**Comment by jdries** [comment]
@tbanyai  never mind, was working on notebook just now, so added a json dump of the graph

**Comment by m-mohr** [comment]
@jdries Could you make it a valid process by wrapping it in `{"process_graphs": ... }`, please?

**Comment by jdries** [comment]
Yes, done!

**Comment by m-mohr** [comment]
Thanks.

**Comment by GreatEmerald** [comment]
I just added ours, see commit above.

**Comment by m-mohr** [comment]
Thanks!
