### ISSUE TITLE
eo:mgrs in JRC usecase and context parameter in reducer

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-usecases#8]
@kempenep I have some questions regarding your use case:

1. Could you please clarify what `eo:mgrs` refers to? It doesn't seem to be a valid STAC field so how is the property in the metadata defined that you query for in your use case?

2. The node below has a context given, but it's not used anywhere in the sub-process. That doesn't really work that way / is not valid according to the spec and thus we can't run it on other back-ends. How could that be improved?

3. Where do I get the BRP_Gewaspercelen_2017.gdb from?

```
        "aggreg1": {
            "process_id": "aggregate_spatial",
            "description": "aggregate spatial using mean value",
            "arguments": {
                "data": {"from_node": "maskedNdvi"},
                "geometries": {
                    "type": "file",
                    "path": "BRP_Gewaspercelen_2017.gdb"
                },
                "context": {
                    "buffer": -10,
                    "srcnodata": 0
                },
                "reducer": {
                    "process_graph": {
                        "mean": {
                            "process_id": "mean",
                            "arguments": {
                                "data": {"from_parameter": "data"}
                            },
                            "result": true
                        }
                    }
                }
            }
        },
```

**Comment by kempenep** [comment]
1) I used eo:mgrs to select a single MGRS tile in the collection (as an alternative to the bounding box). You can easily omit this.
2) I probably mis-understood this context. It is described as "Additional data to be passed to the reducer". As there was no option for the buffer nor srcnodata, I mis-used this for that.
3) I have created an extract of the gdb data in SQLite format [here](https://github.com/Open-EO/openeo-usecases/tree/master/jrc_agriculture_monitoring_usecase/data)
